price_tracker/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views


app_name = 'account'
urlpatterns = [
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_change/", views.PassChangeView.as_view(), name="password_change"),
    path("password_reset/", views.PassResetView.as_view(), name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>", views.PassResetConfirmView.as_view(), name="password_reset_confirm"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/<int:pk>/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("profile/delete/<int:pk>", views.ProfileDeleteView.as_view(), name="profile_delete"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("register_confirm/<uidb64>/<token>", views.RegisterConfirmView.as_view(), name="register_confirm"),
    path("email_change/", views.EmailChangeView.as_view(), name="email_change"),
    path("email_change_confirm/<uidb64>/<token>/<email>", views.EmailChangeConfirmView.as_view(), name="email_change_confirm"),
]

price_tracker/core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("terms/", views.terms, name="terms"),
]

price_tracker/price_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('product/', include('products.urls')),
]

price_tracker/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    email = models.EmailField(unique=True)
    
    def __str__(self) -> str:
        return self.username

price_tracker/accounts/views.py
from django.contrib.auth.tokens import default_token_generator
from django.http.response import HttpResponse as HttpResponse
from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_protect
from django.views.decorators.cache import never_cache
from django.urls import reverse_lazy
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ImproperlyConfigured, ValidationError
from django.http import HttpResponseRedirect
from django.utils.http import urlsafe_base64_decode
from django.views.decorators.debug import sensitive_post_parameters
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import UpdateView, DeleteView, FormView
from django.views.generic.base import TemplateView
from django.contrib.auth.views import (
    LoginView, 
    PasswordResetView, 
    PasswordResetConfirmView,
    PasswordChangeView,
)

from .forms import (
    UserModel,
    LoginForm, 
    PassChangeForm, 
    PassResetForm, 
    SetPassForm, 
    UserUpdateForm,
    UserDeleteForm,
    RegisterForm,
    EmailChangeForm,
)


# auth
class AccountLoginView(LoginView):
    form_class = LoginForm
    template_name = 'accounts/login.html'
    
    def form_valid(self, form):
        messages.success(self.request, f'¡Bienvenido <b>{form.get_user()}</b>!')
        return super().form_valid(form)


# password
class PassChangeView(SuccessMessageMixin, PasswordChangeView):
    form_class = PassChangeForm
    template_name = 'accounts/password_change_form.html'
    success_url = reverse_lazy("account:profile")
    success_message = "¡Contraseña actualizada!"


class PassResetView(SuccessMessageMixin, PasswordResetView):
    form_class = PassResetForm
    template_name = 'accounts/password_reset_form.html'
    email_template_name = 'emails/password_reset_email.html'
    success_url = reverse_lazy("core:home")
    success_message = ("Le enviamos instrucciones por correo electrónico para configurar su contraseña, "
                        "si existe una cuenta con el correo electrónico que ingresó. Debería recibirlos en breve. "
                        "Si no recibe un correo electrónico, asegúrese de haber ingresado la dirección con la que se registró y "
                        "verifique su carpeta de correo no deseado."
                        )

    
class PassResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    form_class = SetPassForm
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy("account:login")
    success_message = "¡Se ha actualizado su contraseña!. Ahora puede continuar e ingresar."


# profile
class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'
    
    
class ProfileUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = get_user_model()
    form_class = UserUpdateForm
    template_name = 'accounts/profile_update.html'
    success_url = reverse_lazy("account:profile")
    success_message = "¡Información Actualizada!"
    
    
class ProfileDeleteView(SuccessMessageMixin, LoginRequiredMixin, DeleteView):
    model = get_user_model()
    form_class = UserDeleteForm
    template_name = 'accounts/profile_delete.html'
    success_url = reverse_lazy("core:home")
    success_message = "Lamentamos que te vayas."
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['initial'] = {'username': self.request.user.username}
        return kwargs
    

# register
class RegisterView(SuccessMessageMixin, FormView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy("account:login")
    success_message = '¡Bienvenido! Revisa tu correo electronico y sigue las instrucciones.'

    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "request": self.request,
        }
        
        form.save(**opts)
        return super().form_valid(form)


INTERNAL_ACTIVATION_SESSION_TOKEN = "_account_activation_token"

class RegisterConfirmView(TemplateView):
    template_name = 'accounts/register_confirm.html' 
    reset_url_token = "activation"
    token_generator = default_token_generator

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        if "uidb64" not in kwargs or "token" not in kwargs:
            raise ImproperlyConfigured(
                "The URL path must contain 'uidb64' and 'token' parameters."
            )

        self.validlink = False
        self.user = get_user(kwargs["uidb64"])
        if self.user is not None:
            token = kwargs["token"]
            if token == self.reset_url_token:
                session_token = self.request.session.get(INTERNAL_ACTIVATION_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                token_valid = self.token_generator.check_token(self.user, token)
                if token_valid:
                    # Store the token in the session and redirect to the
                    # view at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_ACTIVATION_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(
                        token, self.reset_url_token
                    )
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.validlink:
            context["validlink"] = True
            del self.request.session[INTERNAL_ACTIVATION_SESSION_TOKEN]
            self.user.is_active = True
            self.user.save()
        else:
            context["validlink"] = False
        return context


# email
class EmailChangeView(SuccessMessageMixin, FormView):
    template_name = 'accounts/email_change_form.html'
    form_class = EmailChangeForm
    success_url = reverse_lazy("account:profile")
    success_message = "¡Verifica el correo para que se actualizado!"
    
    @method_decorator(csrf_protect)
    def dispatch(self, *args, **kwargs):
        self.user = self.request.user
        return super().dispatch(*args, **kwargs)
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.user
        return kwargs
    
    def form_valid(self, form):
        opts = {
            "use_https": self.request.is_secure(),
            "request": self.request,
        }
        
        form.save(**opts)
        return super().form_valid(form)
    

class EmailChangeConfirmView(TemplateView):
    template_name = 'accounts/email_change_confirm.html'
    reset_url_token = "email-validation"
    token_generator = default_token_generator
    
    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        if "uidb64" not in kwargs or "token" not in kwargs or "email" not in kwargs:
            raise ImproperlyConfigured(
                "The URL path must contain 'uidb64' 'token'and 'email' parameters."
            )

        self.validlink = False
        self.user = get_user(kwargs["uidb64"])
        self.email = urlsafe_base64_decode(kwargs["email"]).decode()
        
        if self.user is not None:
            token = kwargs["token"]
            if token == self.reset_url_token:
                session_token = self.request.session.get(INTERNAL_ACTIVATION_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            else:
                token_valid = self.token_generator.check_token(self.user, token)
                if token_valid:
                    # Store the token in the session and redirect to the
                    # view at a URL without the token. That
                    # avoids the possibility of leaking the token in the
                    # HTTP Referer header.
                    self.request.session[INTERNAL_ACTIVATION_SESSION_TOKEN] = token
                    redirect_url = self.request.path.replace(
                        token, self.reset_url_token
                    )
                    return HttpResponseRedirect(redirect_url)

        # Display the "Password reset unsuccessful" page.
        return self.render_to_response(self.get_context_data())


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.validlink:
            context["validlink"] = True
            del self.request.session[INTERNAL_ACTIVATION_SESSION_TOKEN]
            self.user.email = self.email
            self.user.save()
        else:
            context["validlink"] = False
        return context
    

def get_user(uidb64):
    try:
        # urlsafe_base64_decode() decodes to bytestring
        uid = urlsafe_base64_decode(uidb64).decode()
        user = UserModel._default_manager.get(pk=uid)
    except (
        TypeError,
        ValueError,
        OverflowError,
        UserModel.DoesNotExist,

price_tracker/templates/accounts/base.html
{% extends "core/base.html" %}

{% load static %}

{% block nav %}
    {% include "core/navbar_base.html" %}
{% endblock nav %}

{% block content %}
    <div class="row">
        {% include "accounts/sidebar.html" %}
        {% block subcontent %}
        {% endblock subcontent %}
    </div>
{% endblock content %}

price_tracker/templates/accounts/email_change_confirm.html
{% extends "core/main.html" %}

{% load i18n %}

{% block content %}

{% if validlink %}

<div class="alert alert-success" role="alert">
    <p>{% translate "¡Gracias por confirmar tu correo electrónico!" %}</p>
</div>


{% else %}

<div class="alert alert-warning" role="alert">
    <p>
        {% translate "El enlace de activación de cuenta es inválido, posiblemente debido a que ya ha sido usado." %}
    </p>
</div>

{% endif %}

{% endblock %}

price_tracker/templates/accounts/email_change_form.html
{% extends "accounts/base.html" %}

{% load static %}

{% block subcontent %}

<div class="col">
    <div class="card">
        <h5 class="card-header">{{ user.username }}</h5>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% if form.new_email.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.new_email.errors }}</div>
                {% endif %}
                <p>{{ form.new_email }}</p>
                <button class="btn btn-outline-dark btn-sm" type="submit">Verificar Email</button>
            </form>
        </div>
    </div>
</div>

{% endblock subcontent %}

price_tracker/templates/accounts/login.html
{% extends "core/form_base.html" %}

{% load i18n static %}
{% load static %}

{% block form %}

<div class="p-5">
    <h3>Iniciar sesión</h3>
</div>

{% if form.errors and not form.non_field_errors %}
    <p class="errornote">
        {% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
    </p>
{% endif %}

{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger" role="alert">{{ error }}</div>
    {% endfor %}
{% endif %}

{% if user.is_authenticated %}
    <p class="errornote">
        {% blocktranslate trimmed %}
        You are authenticated as {{ username }}, but are not authorized to
        access this page. Would you like to login to a different account?
        {% endblocktranslate %}
    </p>
{% endif %}

<div class="p-3">
    <form method="post" action="{% url 'account:login' %}">
        {% csrf_token %}
        {% if form.username.errors %}
            <div class="alert alert-danger" role="alert">{{ form.username.errors }}</div>
        {% endif %}
        <p>{{ form.username }}</p>

        {% if form.password.errors %}
            <div class="alert alert-danger" role="alert">{{ form.password.errors }}</div>
        {% endif %}
        <p>{{ form.password }}</p>

        <button class="btn btn-outline-dark btn-sm" type="submit">{% translate 'Log in' %}</button>
    </form>
</div>
<div class="p-5">
    <div class=" border-top">
        <small>
            <a href="{% url 'account:register' %}" class="link-underline-light link-opacity-50-hover">Registrarse</a>
        </small>
        <br>
        <small>
            <a href="{% url 'account:password_reset' %}" class="link-underline-light link-opacity-50-hover">Olvidé mi contraseña</a>
        </small>
    </div>
</div>

{% endblock form %}

price_tracker/templates/accounts/password_change_form.html
{% extends "accounts/base.html" %}

{% load static %}
{% load i18n static %}

{% block subcontent %}

<div class="col">
    <div class="card">
        <div class="card-header">
            <h5>{{ title }}</h5>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                {% if form.errors %}
                    <p class="errornote">
                    {% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
                    </p>
                {% endif %}
                
                <p>
                    {% translate 'Please enter your old password, for security’s sake, and then enter your new password twice so we can verify you typed it in correctly.' %}
                </p>

                {% if form.old_password.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.old_password.errors }}</div>
                {% endif %}
                <p>{{ form.old_password.label_tag }}{{ form.old_password }}</p>

                {% if form.new_password1.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.new_password1.errors }}</div>
                {% endif %}
                <p>{{ form.new_password1.label_tag }}{{ form.new_password1 }}</p>

                {% if form.new_password2.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.new_password2.errors }}</div>
                {% endif %}
                <p>{{ form.new_password2.label_tag }}{{ form.new_password2 }}</p>

                <button class="btn btn-outline-dark btn-sm" type="submit">{% translate 'Change my password' %}</button>
            </form>
        </div>
    </div>
</div>
{% endblock subcontent %}

price_tracker/templates/accounts/password_reset_confirm.html
{% extends "core/form_base.html" %}

{% load i18n static %}
{% load static %}

{% block form %}

{% if validlink %}

<div class="p-5">
    <h3>Ingresar nueva contraseña</h3>
</div>

<p>{% translate "Please enter your new password twice so we can verify you typed it in correctly." %}</p>

<div class="p-3">
    <form method="post">
        {% csrf_token %}
        
        <p class="fw-bold">{{ form.user.get_username }}</p>

        {% if form.new_password1.errors %}
            <div class="alert alert-danger" role="alert">{{ form.new_password1.errors }}</div>
        {% endif %}
        <p>{{ form.new_password1 }} </p>

        {% if form.new_password2.errors %}
            <div class="alert alert-danger" role="alert">{{ form.new_password2.errors }}</div>
        {% endif %}
        <p>{{ form.new_password2 }} </p>

        <button class="btn btn-outline-dark btn-sm" type="submit">{% translate 'Change my password' %}</button>
    </form>
</div>

{% else %}

<div class="alert alert-warning" role="alert">
    <p>
        {% translate "The password reset link was invalid, possibly because it has already been used.  Please request a new password reset." %}
    </p>
</div>

{% endif %}

{% endblock form %}

price_tracker/templates/accounts/password_reset_form.html
{% extends "core/form_base.html" %}

{% load static %}
{% load i18n static %}

{% block form %}

<div class="p-5">
    <h3>Recuperar contraseña</h3>
</div>

<p>{% translate 'Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.' %}</p>

<div class="p-3">
    <form method="post">
        {% csrf_token %}
        {% if form.email.errors %}
            <div class="alert alert-danger" role="alert">{{ form.email.errors }}</div>
        {% endif %}
        <p>{{ form.email.label_tag }}{{ form.email }}</p>
        <button class="btn btn-outline-dark btn-sm" type="submit">{% translate 'Reset my password' %}</button>
    </form>
</div>
<div class="p-5">
    <div class=" border-top">
        <small>
            <a href="{% url 'account:register' %}" class="link-underline-light link-opacity-50-hover">Registrarse</a>
        </small>
        <br>
        <small>
            <a href="{% url 'account:login' %}" class="link-underline-light link-opacity-50-hover">{% translate 'Log in' %}</a>
        </small>
    </div>
</div>

{% endblock form %}

price_tracker/templates/accounts/profile.html
{% extends "accounts/base.html" %}

{% load static %}

{% block subcontent %}
    <div class="col">
            <div class="card">
                <h5 class="card-header">{{ user.username }}</h5>
                <div class="card-body">
                    <h5 class="card-title">{{ user.first_name }} {{ user.last_name }}</h5>
                    <h5 class="card-title">{{ user.email }}</h5>
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary">Fecha de creación: {{ user.date_joined}}</small>
                </div>
            </div>
    </div>
{% endblock subcontent %}

price_tracker/templates/accounts/profile_delete.html
{% extends "accounts/base.html" %}

{% load static %}

{% block subcontent %}

<div class="col">
    <div class="card">
        <h5 class="card-header">{{ user.username }}</h5>
        <div class="card-body">

            {% if form.non_field_errors %}
                {% for error in form.non_field_errors %}
                    <div class="alert alert-danger" role="alert">{{ error }}</div>
                {% endfor %}
            {% endif %}

            <form method="post">
                {% csrf_token %}
                <p>Por favor, ingresa tu contraseña para confirmar la eliminación de tu cuenta.</p>
                {% if form.username.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.username.errors }}</div>
                {% endif %}
                <p>{{ form.username }}</p>

                {% if form.password.errors %}
                    <div class="alert alert-danger" role="alert">{{ form.password.errors }}</div>
                {% endif %}
                <p>{{ form.password }}</p>
                <button class="btn btn-outline-danger btn-sm" type="submit">Confirmar</button>
            </form>
        </div>
    </div>
</div>

{% endblock subcontent %}

price_tracker/templates/accounts/profile_update.html
{% extends "accounts/base.html" %}

{% load static %}

{% block subcontent %}

<div class="col">
  <div class="card">
      <h5 class="card-header">{{ user.username }}</h5>
      <form method="post">
          <div class="card-body">    
              {% csrf_token %}
              <p>{{ form.first_name }} </p>
              <p>{{ form.last_name }} </p>
              <button class="btn btn-outline-dark btn-sm" type="submit" value="Update">Guardar</button>
          </div>
          <div class="card-body">
              <div class="row">
                  <div class="col">
                      <p>{{ form.email }}</p>
                  </div>
                  <div class="col">
                      <a href="{% url "account:email_change" %}" class="btn btn-outline-dark btn-sm">
                          Cambiar
                      </a>
                  </div>
              </div>
              <div class="row">
                  <div class="col">
                      <p><input class="form-control h-auto form-control-solid" placeholder="Contraseña" disabled></p>
                  </div>
                  <div class="col">
                      <a href="{% url "account:password_change" %}" class="btn btn-outline-dark btn-sm">
                          Cambiar
                      </a>
                  </div>
              </div>
          </div>
      </form>
      <div class="card-body">
          <a href="{% url "account:profile_delete" user.id %}" class="btn btn-outline-danger btn-sm">
              Eliminar cuenta
          </a>
      </div>
  </div>
</div>


{% endblock subcontent %}

price_tracker/templates/accounts/register.html
{% extends "core/form_base.html" %}

{% load i18n static %}
{% load static %}

{% block form %}

<div class="p-1">
    <h3>Registrarse</h3>
</div>

{% if form.errors and not form.non_field_errors %}
    <p class="errornote">
        {% blocktranslate count counter=form.errors.items|length %}Please correct the error below.{% plural %}Please correct the errors below.{% endblocktranslate %}
    </p>
{% endif %}


<div class="p-3">
    <form method="post" action="{% url 'account:register' %}">
        {% csrf_token %}
        {% if form.username.errors %}
            <div class="alert alert-danger" role="alert">{{ form.username.errors }}</div>
        {% endif %}
        <p>{{ form.username }} </p>
        {% if form.first_name.errors %}
            <div class="alert alert-danger" role="alert">{{ form.first_name.errors }}</div>
        {% endif %}
        <p>{{ form.first_name }} </p>
        {% if form.last_name.errors %}
            <div class="alert alert-danger" role="alert">{{ form.last_name.errors }}</div>
        {% endif %}
        <p>{{ form.last_name }} </p>
        {% if form.email.errors %}
            <div class="alert alert-danger" role="alert">{{ form.email.errors }}</div>
        {% endif %}
        <p>{{ form.email }} </p>
        {% if form.password1.errors %}
            <div class="alert alert-danger" role="alert">{{ form.password1.errors }}</div>
        {% endif %}
        <p>{{ form.password1 }} </p>
        {% if form.password2.errors %}
            <div class="alert alert-danger" role="alert">{{ form.password2.errors }}</div>
        {% endif %}
        <p>{{ form.password2 }} </p>
        <button class="btn btn-outline-dark btn-sm" type="submit">Registrarse</button>
    </form>
</div>
<div class="p-5">
    <div class=" border-top">
        <small>
            <a href="{% url 'account:login' %}" class="link-underline-light link-opacity-50-hover">Iniciar sesión</a>
        </small>
    </div>
</div>

{% endblock form %}

price_tracker/templates/accounts/register_confirm.html
{% extends "core/main.html" %}

{% load i18n %}

{% block content %}

{% if validlink %}

<div class="alert alert-success" role="alert">
    <p>{% translate "¡Gracias por confirmar tu correo electrónico!" %}</p>
</div>

<p>
    <a href="{% url 'account:login' %}" class="link-underline-light link-opacity-50-hover">
        {% translate 'Log in' %}
    </a>
</p>

{% else %}

<div class="alert alert-warning" role="alert">
    <p>
        {% translate "El enlace de activación de cuenta es inválido, posiblemente debido a que ya ha sido usado." %}
    </p>
</div>

{% endif %}

{% endblock %}

price_tracker/templates/accounts/sidebar.html
{% extends "core/sidebar_base.html" %}

{% load static %}

{% block sidebarAdd %}

<ul class="list-unstyled ps-0">
    <!--<li class="mb-1">
        <button class="btn btn-toggle d-inline-flex align-items-center rounded border-0 collapsed" 
                data-bs-toggle="collapse" 
                data-bs-target="#account-collapse" 
                aria-expanded="false">
            Perfil
        </button>
        <div class="collapse" id="account-collapse">
            <ul class="btn-toggle-nav list-unstyled fw-normal pb-1 small">
                <li>
                </li>
            </ul>
        </div>
    </li>-->
    <li>
        <form method="get" action="{% url 'account:profile_update' user.id %}">
            <button type="submit" class="btn btn-sm">
                <i class="bi bi-gear"></i> Ajustes
            </button>
        </form>
    </li>
    <li>
        <form method="post" action="{% url 'account:logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-sm">
                <i class="bi bi-box-arrow-left"></i> Cerrar sesión
            </button>
        </form>
    </li>
    <li class="border-top my-3"></li>
</ul>

{% endblock sidebarAdd %}