price_tracker/accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView

from . import views


app_name = 'account'
urlpatterns = [
    path("login/", views.AccountLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("password_change/", views.PassChangeView.as_view(), name="password_change"),
    path("password_reset/", views.PassResetView.as_view(), name="password_reset"),
    path("password_reset_confirm/<uidb64>/<token>", views.PassResetConfirmView.as_view(), name="password_reset_confirm"),
    path("profile/", views.ProfileView.as_view(), name="profile"),
    path("profile/update/<int:pk>/", views.ProfileUpdateView.as_view(), name="profile_update"),
    path("profile/delete/<int:pk>", views.ProfileDeleteView.as_view(), name="profile_delete"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("register_confirm/<uidb64>/<token>", views.RegisterConfirmView.as_view(), name="register_confirm"),
    path("email_change/", views.EmailChangeView.as_view(), name="email_change"),
    path("email_change_confirm/<uidb64>/<token>/<email>", views.EmailChangeConfirmView.as_view(), name="email_change_confirm"),
]

price_tracker/core/urls.py
from django.urls import path
from . import views


app_name = 'core'
urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("terms/", views.terms, name="terms"),
]

price_tracker/price_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('account/', include('accounts.urls')),
    path('product/', include('products.urls')),
]

price_tracker/products/urls.py
from django.urls import path
from . import views


app_name = 'product'
urlpatterns = [
    path("", views.home, name="home"),
    path("<int:pk>", views.product_details, name="product"),
]

price_tracker/core/models.py
from django.db import models


class BaseModel(models.Model):
    name = models.CharField(verbose_name='Name', max_length=200, unique=True)
    description = models.CharField(verbose_name='Description', max_length=500, blank=True)
    enabled = models.BooleanField(verbose_name='Enabled', default=True, help_text='Default: True')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Date Created')
    updated_at = models.DateTimeField(auto_now=True, verbose_name='Last Updated')

    class Meta:
        abstract = True

price_tracker/core/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'core/main.html')

    
def about(request):
    pass


def terms(request):
    pass

price_tracker/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="es" class="h-100">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}Price Tracker{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/logo.svg' %}" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css" rel="stylesheet">
        {% block styles %}
        {% endblock styles %}
    </head>
    <body class="d-flex flex-column h-100">
        <div class="container">
                <!-- Main-->
                <main class="flex-shrink-0">
                    {% block nav %}
                        {% include "core/navbar.html" %}
                    {% endblock nav %}
                    {% include "core/messages.html" %}
                    <div class="container">
                        {% block content %}
                        {% endblock content %}
                    </div>
                </main>
        </div>
        <!-- Footer-->
        {% include "core/footer.html" %}

        <!-- Core theme JS (includes Bootstrap)-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
        {% block scripts %}
        {% endblock scripts %}
    </body>
</html>

price_tracker/templates/core/footer.html
<footer class="footer mt-auto py-3">
    <div class="container text-center">
        <div class="row">
            <div class="col">
                <div class="single-box">
                    <div class="socials">
                            <a href="/"><i class="bi bi-telegram fs-3 text-dark"></i></a>
                            <a href="/"><i class="bi bi-github fs-3 text-dark"></i></a>
                    </div>
                </div>
            </div>
        </div>
        <!---<div class="row">
            <div class="col">
                <div class="single-box">
                    <span class="text-body-secondary">&copy; 2024 Price Tracker</span>
                </div>
            </div>
        </div>-->
        <div class="row">
            <div class="col">
                <div class="single-box">
                    <small class="me-3">
                        <a href="{% url 'core:terms' %}" class="link-underline-light link-opacity-50-hover">Terminos y condiciones</a>
                    </small>
                    <small class="single-box">
                        <a href="{% url 'core:about' %}" class="link-underline-light link-opacity-50-hover">Acerca</a>
                    </small>
                </div>
            </div>
        </div>
    </div>
</footer>

price_tracker/templates/core/form_base.html
{% extends "core/base.html" %}

{% load static %}

{% block nav %}
    {% include "core/navbar_base.html" %}
{% endblock nav %}


{% block content %}

<!-- Section-->
<section class="py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-4 col col-sm-9">
                <div class="text-center position-relative overflow-hidden">
                    {% block form %}
                    {% endblock form %} 
                </div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

price_tracker/templates/core/main.html
{% extends "core/base.html" %}

{% load static %}
{% load humanize %}


{% block content %}

<h1>Main</h1>

{% endblock content %}

price_tracker/templates/core/messages.html
{% if messages %}
    {% for message in messages %}
        {% if message.tags == 'success' %}
            <div class="alert alert-success alert-dismissible  fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'error' %}
            <div class="alert alert-danger alert-dismissible  fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'info' %}
            <div class="alert alert-info alert-dismissible  fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message|safe|escape }}
            </div>
        {% elif message.tags == 'warning' %}
            <div class="alert alert-warning alert-dismissible  fade show" role="alert">
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                {{ message|safe|escape }}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

price_tracker/templates/core/navbar.html
{% extends "core/navbar_base.html" %}

{% load static %}

{% block navbarAdd %}

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <form class="d-flex flex-grow-1 p-3" role="search" method="GET" action="{% url 'product:home' %}">
        <input class="form-control me-2 flex-grow-1" type="search" placeholder="Buscar..." name="q" aria-label="Search">
        <button class="btn btn-light" type="submit">Buscar</button>
    </form>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        {% if user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:profile' %}">
                    <i class="bi bi-person-fill"></i> {{ user.username }}
                </a>
            </li>
        {% else %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'account:login' %}">
                <i class="bi bi-person-circle fs-3"></i>
            </a>
        </li>
        {% endif %}
    </ul>
</div>

{% endblock navbarAdd %}

price_tracker/templates/core/navbar_base.html
{% load static %}

<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand fw-bold" href="{% url 'core:home' %}">
            <img src="{% static 'assets/logo.svg' %}" alt="Logo" width="35" height="35" class="d-inline-block align-text-top">
            Price Tracker</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        {% block navbarAdd %}
        {% endblock navbarAdd %}
    </div>
</nav>

price_tracker/templates/core/sidebar_base.html
{% load static %}

<div class="col-4 col-sm-2">
        <a href="{% url 'account:profile' %}" class="d-flex align-items-center pb-3 mb-3 link-body-emphasis text-decoration-none border-bottom">
            <span class="fs-5 fw-semibold"><i class="bi bi-person-fill"></i> {{ user.username }}</span>
        </a>
        {% block sidebarAdd %}
        {% endblock sidebarAdd %}
</div>